### ISSUE TITLE
Using derive_more to derive Arithmetic operators.

### ISSUE THREAD

**Issue by JelteF** [paholg/dimensioned#25]
When I saw this on Reddit this seemed like a library that can make perfect use of my [derive_more](https://jeltef.github.io/derive_more/derive_more/) lib. 

Would you be interested in a pull request to use that instead of te macros in https://github.com/paholg/dimensioned/blob/master/src/make_units.rs

**Comment by paholg** [comment]
I'm definitively open to it, but I'm not sure it would work properly. Because the units represent powers, they don't have the same operations performed as the values do.

For example, when you add two `SI<V, U>`s, the result should be `SI<Sum<V, V>, U`, or when you multiply `SI<V, U1>` by `SI<V, U2>`, the result should be `SI<Prod<V, V>, Sum<U1, U2>>`.

**Comment by paholg** [comment]
Feel free to re-open if you think you can make your macros work for dimensioned.
